# Generated by Django 2.1.5 on 2019-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Login',
            fields=[
                ('admin_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='New_User',
            fields=[
                ('vip_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(default='', max_length=50)),
                ('vip_name', models.CharField(max_length=50)),
                ('vip_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('vip_birthday', models.DateField()),
                ('vip_phone', models.CharField(max_length=30)),
                ('vip_email', models.EmailField(max_length=254, unique=True)),
                ('vip_duriation', models.CharField(max_length=30)),
                ('vip_level', models.IntegerField()),
                ('vip_password', models.CharField(default='123456', max_length=256)),
            ],
            options={
                'ordering': ('-vip_id',),
            },
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='123456', max_length=256)),
            ],
        ),
    ]
