# Generated by Django 2.1 on 2019-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('vip_id', models.AutoField(primary_key=True, serialize=False)),
                ('vip_name', models.CharField(max_length=50)),
                ('vip_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('vip_birthday', models.DateField()),
                ('vip_phone', models.CharField(max_length=30)),
                ('vip_email', models.EmailField(max_length=254, unique=True)),
                ('vip_duriation', models.CharField(max_length=30)),
                ('vip_level', models.IntegerField()),
            ],
            options={
                'ordering': ('-vip_id',),
            },
        ),
    ]
