# Generated by Django 2.1 on 2019-11-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='New_User',
        ),
    ]
