# Generated by Django 2.1 on 2019-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191120_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='vip_password',
            field=models.CharField(default='123456', max_length=256),
        ),
    ]
