# Generated by Django 2.1.5 on 2019-12-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191220_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='vip_password',
        ),
    ]
