# Generated by Django 2.1.5 on 2019-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_new_user_vip_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='login_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User_Login', unique=True),
        ),
    ]
