# Generated by Django 2.1.5 on 2019-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_new_user_vip_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='123456', max_length=256)),
            ],
        ),
    ]
