# Generated by Django 2.1.5 on 2019-11-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='login_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
