# Generated by Django 2.1.8 on 2019-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ly_app', '0001_initial'),
        ('users', '0004_auto_20191220_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='courseById',
            field=models.ManyToManyField(to='ly_app.course'),
        ),
    ]
