# Generated by Django 2.1.8 on 2019-12-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ly_app', '0002_auto_20191229_0045'),
        ('users', '0005_new_user_coursebyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='coachById',
            field=models.ManyToManyField(to='ly_app.coach'),
        ),
    ]
