# Generated by Django 2.1.5 on 2019-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_new_user_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Login',
            fields=[
                ('admin_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
    ]
