# Generated by Django 2.1 on 2019-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyData',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('hight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('chest', models.DecimalField(decimal_places=1, max_digits=3)),
                ('waist', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hip', models.DecimalField(decimal_places=1, max_digits=3)),
                ('queith', models.DecimalField(decimal_places=1, max_digits=3)),
                ('maxh', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
