# Generated by Django 2.1.5 on 2019-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodydata',
            name='BMI',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='chest',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='hight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='hip',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='maxh',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='queith',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='waist',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
