# Generated by Django 2.1.5 on 2019-12-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0003_testdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
