# Generated by Django 2.1.5 on 2019-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0004_delete_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partcode', models.CharField(max_length=16)),
                ('partname', models.CharField(max_length=10)),
            ],
        ),
    ]
