# Generated by Django 2.1.5 on 2019-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0005_bodyparts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodytestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bodyparts',
            name='id',
        ),
        migrations.AlterField(
            model_name='bodyparts',
            name='partcode',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bodyteststandard',
            name='partcode',
            field=models.ForeignKey(on_delete=True, related_name='Parts_Test', to='wly_app.BodyParts'),
        ),
    ]
