# Generated by Django 2.1.5 on 2019-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191220_1724'),
        ('wly_app', '0006_auto_20191220_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPysicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdata', models.IntegerField()),
                ('partcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wly_app.BodyParts')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.New_User', to_field='login_name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userpysicaltest',
            unique_together={('user_name', 'partcode')},
        ),
    ]
