# Generated by Django 2.1.5 on 2019-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0007_auto_20191220_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='starlevel',
            fields=[
                ('starcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stardisplay', models.CharField(max_length=30)),
            ],
        ),
    ]
