# Generated by Django 2.1.5 on 2019-12-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0008_starlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyteststandard',
            name='comment',
            field=models.CharField(default='c', max_length=60),
        ),
    ]
