# Generated by Django 2.1.5 on 2019-12-26 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191220_1724'),
        ('wly_app', '0009_bodyteststandard_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createon', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('testlevel', models.CharField(max_length=30)),
                ('partcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wly_app.BodyParts')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.New_User', to_field='login_name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertestrecord',
            unique_together={('user_name', 'createon')},
        ),
    ]
