# Generated by Django 2.1.5 on 2019-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0010_auto_20191226_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('grade', models.IntegerField(primary_key=True, serialize=False, verbose_name='成绩')),
                ('level', models.CharField(max_length=10, verbose_name='等级')),
            ],
        ),
    ]
