# Generated by Django 2.1.5 on 2019-12-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0012_auto_20191227_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertestrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usertestrecord',
            name='partcode',
        ),
        migrations.RemoveField(
            model_name='usertestrecord',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='UserTestRecord',
        ),
    ]
