# Generated by Django 2.1.5 on 2019-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0013_auto_20191227_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('coursename', models.CharField(max_length=30, verbose_name='课程名称')),
            ],
        ),
    ]
