# Generated by Django 2.1.5 on 2019-12-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0014_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courselevel', models.CharField(max_length=10, verbose_name='课程等级')),
                ('frequency', models.IntegerField(verbose_name='次数')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wly_app.Courses')),
                ('partcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wly_app.BodyParts')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='partcourse',
            unique_together={('partcode', 'courseid')},
        ),
    ]
