# Generated by Django 2.1.5 on 2019-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0015_auto_20191227_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='decription',
            field=models.CharField(default='', max_length=150, verbose_name='课程介绍'),
        ),
    ]
