# Generated by Django 2.1.5 on 2019-12-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0016_courses_decription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partcourse',
            unique_together={('partcode', 'courseid', 'courselevel')},
        ),
    ]
