# Generated by Django 2.1.5 on 2019-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0017_auto_20191227_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='pic',
            field=models.CharField(default='./', max_length=150, verbose_name='图片路径'),
        ),
    ]
