# Generated by Django 2.1.5 on 2019-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0018_courses_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcourse',
            name='frequency',
            field=models.CharField(max_length=30, verbose_name='次数'),
        ),
    ]
