# Generated by Django 2.1.5 on 2019-12-28 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0019_auto_20191228_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyteststandard',
            name='createon',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
