# Generated by Django 2.1.5 on 2019-12-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0020_bodyteststandard_createon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyteststandard',
            name='createon',
        ),
    ]
