# Generated by Django 2.1.5 on 2019-12-28 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0021_remove_bodyteststandard_createon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodydata',
            name='createon',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
