# Generated by Django 2.1.5 on 2019-12-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0022_bodydata_createon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyData',
        ),
    ]
