# Generated by Django 2.1.5 on 2019-12-28 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191220_1724'),
        ('wly_app', '0023_delete_bodydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=1, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=1, max_digits=5)),
                ('queith', models.DecimalField(decimal_places=1, max_digits=5)),
                ('maxh', models.DecimalField(decimal_places=1, max_digits=5)),
                ('BMI', models.DecimalField(decimal_places=1, max_digits=5)),
                ('createon', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.New_User', to_field='login_name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bodydata',
            unique_together={('user_name', 'createon')},
        ),
    ]
