# Generated by Django 2.1.5 on 2019-12-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wly_app', '0024_auto_20191228_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyparts',
            name='parttestdesc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bodyparts',
            name='parttestname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
