# Generated by Django 2.1.8 on 2019-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('coachid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10)),
                ('age', models.IntegerField()),
                ('sense', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='接收数据时间')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('spendtime', models.CharField(max_length=30, unique=True)),
                ('starttime', models.CharField(max_length=30, unique=True)),
                ('classroom', models.CharField(max_length=30, unique=True)),
                ('person', models.IntegerField()),
            ],
        ),
    ]
