# Generated by Django 2.1.5 on 2019-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ly_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('coachid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
