# Generated by Django 2.1.8 on 2019-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ly_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
